import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Counter from '../components/Counter'

import { useState } from 'react'

export default function Home() {
  const [counts, setCounts] = useState([])

  const add = () =>{

    var add = counts
    add++
    setCounts(add)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
      <li>
        <Link href="/posts/firstpost">
          <a>firstpost</a>
        </Link>
      </li>
      <li>
        <Link href="/posts/secondpost">
          <a>secondpost</a>
        </Link>
      </li>
    </ul>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
          {/* <Link href="/posts/firstpost" className={styles.card}>
          <a>firstpost</a>
        </Link> */}
        <Link href="/posts/firstpost" >
          <a className={styles.card}>
            <h2>First Post &rarr;</h2>
            <p>
              First Post
            </p>
          </a>
            </Link>
        <Link href="/posts/secondpost" >
      <a className={styles.card}>
        <h2>secondpost&rarr;</h2>
        <p>
          Second Post
        </p>
      </a>
        </Link>
      
        <Link href="/posts/1" >
      <a className={styles.card}>
        <h2>1&rarr;</h2>
        <p>
          1
        </p>
      </a>
        </Link>

        <a className={styles.card}>

        <button onClick={add}>        
        <h2>COUNT ME &rarr;</h2>
        </button>
      </a>
        <Counter count={counts}  />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
